### ISSUE TITLE
NameError when running example code

### ISSUE THREAD

**Issue by palmeida** [BDI-pathogens/OpenABM-Covid19#1]
I installed this model and tried running the example Python code from the README, but ran into a few issues. Two of them I could figure out: `input_household_file` is now `input_households`; as far as I could understand, you have to create an environment using the model (`env = COVID19IBM(model)`) and then run `simulation = Simulation(env)`, instead of feeding the model directly to `Simulation`, as in the example code.

With that I could create the `Simulation` object, but when I tried to run it with `simulation.simulations(n_simulations=3)` I got a `NameError`:

> NameError: name 'current_action' is not defined

That makes sense, because in [line 168 of `simulation.py`](https://github.com/BDI-pathogens/OpenABM-Covid19/blob/1bc20c04f21b0f301f593588e317232bea2ab8bc/src/COVID19/simulation.py#L168) `current_action` is being used without being defined. 

What can I do to run the simulation?

**Comment by roberthinch** [comment]
Hi Paulo,

Thanks for pointing this out, the Usage section is now updated.

I would recommend running the 3 Jupyter notebooks in the Examples section
which show the simple use cases of the model in Python and then a detailed
analyses of the output of the model.

Best wishes, Rob
