### ISSUE TITLE
Risk-based Quarantining 

### ISSUE THREAD

**Issue by roberthinch** [BDI-pathogens/OpenABM-Covid19#11]
Not all contacts are equal and not all interactions are equally likely to transmit the virus. When deciding who should be quarantined on tracing, use a risk-based approach instead of blanket rules for all contacts.

**Comment by AidanToase** [comment]
Rob - in the risk based calculation do you consider the "impact" of the secondary contact? 

i.e. if index case infects two people with identical individual risks - one might have 100 contacts and the other 20   - arguably the 1st person should have a much higher risk factor even though individually their risk is the same....

One approach to including this would be to include into the risk factor calculation the risk factor of all of the secondary contacts (reduced by the probability of spread from the index case)   This would also mean converting risk factor to a "probability to show symptoms" which might be an easier thing to calibrate anyhow...

**Comment by roberthinch** [comment]
Added in PR #28

**Comment by radka-j** [comment]
This is great, I didn't know this was implemented in the model. 

Is there a description somewhere of how the risk score calculation was implemented and how it can be used? Thanks!
