### ISSUE TITLE
Missing parameter_line_number in some output file names

### ISSUE THREAD

**Issue by RossBoylan** [BDI-pathogens/OpenABM-Covid19#112]
It appears the parameter line number suffix has been omitted from a few of the output file names in `input.c`.

E.g.,  for `ward_output`.
 ```c
	// Concatenate file name
	strcpy(output_file_name, model->params->output_file_dir);
	strcat(output_file_name, "/ward_output");
	strcat(output_file_name, ".csv");
	ward_output_file = fopen(output_file_name, "w");
```
`time_step_hospital_interactions` and `time_step_hospital_output` are the only other ones I see missing the line number, although it's possible the file name passed to `write_network()` has issues too (haven't traced it through).

Every other one looks like this:
```c
	strcpy(output_file_name, model->params->output_file_dir);
	strcat(output_file_name, "/transmission_Run");
	strcat(output_file_name, param_line_number);
	strcat(output_file_name, ".csv");

	output_file = fopen(output_file_name, "w");
```
If the omission was not deliberate, it would probably be good to fix.

Since I'll be running in parallel I'll need more than that anyway, but I thought I might flag it.

**Comment by roberthinch** [comment]
I suspect it was more of an oversight, we've not used this file in any large scale runs yet. Agree it should be standardised.
