### ISSUE TITLE
Can't find documentation of output timeseries

### ISSUE THREAD

**Issue by fhr** [BDI-pathogens/OpenABM-Covid19#127]
The model outputs a set of timeseries for key items, e.g. total_infected, and total_case. 
However, I can't find a dictionary which confirms how each of these is defined. Is there such a thing in the repo somewhere?

In particular I wanted to check this in order to diagnose some unexpected behaviour: when running the model with fraction_asymptomatic set to .16 for all age groups, I get total_case to be consistently around 2.5% of total_infected. I would interpret "total_infected" as "infected including asymptomatic", while "total_case" would be "infected, symptomatic only" - so I would expect one to be .16 of the other.

**Comment by fhr** [comment]
Thaink you Will, that would be a big help.

**Comment by roberthinch** [comment]
Parameter dictionary for time-series added in PR #128.

**Comment by fhr** [comment]
Thanks Will, that is very useful to us.
