### ISSUE TITLE
hospital_admissions output variable is not being populated

### ISSUE THREAD

**Issue by nagyben** [BDI-pathogens/OpenABM-Covid19#137]
I ran the example_101.py with some modifications to show the output data and it seems like `hospital_admissions` and `hospital_admissions_total` are not being populated

```python
import example_utils as utils
import pandas as pd
import plotly

params = utils.get_baseline_parameters()
params.set_param( "n_total", 10000 )
sim = utils.get_simulation( params )
sim.steps( 100 )
timeseries = pd.DataFrame( sim.results )

import plotly.express as px

fig = px.line(timeseries, x="time", y="n_hospital")
fig2 = px.line(timeseries, x="time", y="hospital_admissions")
fig3 = px.line(timeseries, x="time", y="hospital_admissions_total")
fig.show()
fig2.show()
fig3.show()
```

Running this outputs the following:

![newplot](https://user-images.githubusercontent.com/5725246/86928611-b2c1f980-c12c-11ea-9421-9866b7f31c9c.png)

![newplot (1)](https://user-images.githubusercontent.com/5725246/86928621-b5245380-c12c-11ea-803e-dc089a68761d.png)

![newplot (2)](https://user-images.githubusercontent.com/5725246/86928727-da18c680-c12c-11ea-9e85-6421e4ede541.png)

I would expect these two variables to change as `n_hospital` changes

**Comment by brynmathias** [comment]
@nagyben Thanks for flagging this. Tag v0.2 will still have these populated, however the latest version of the ABM which supports nosocomial transmissions does not populate these variables at present.

@p-robot @roberthinch do these need adding back in, or should they be removed from the output?

**Comment by nagyben** [comment]
Could we request that it is added back in?

It would make our lives a lot easier 😄
