### ISSUE TITLE
Manual Contact Tracing - Getting counter-intuitive results for manual_traceable_fraction_random parameter

### ISSUE THREAD

**Issue by ptrein** [BDI-pathogens/OpenABM-Covid19#142]
For your reference, I'm using code merged from the repo on July 2. I'm running a manual contact tracing scenario with a population of 100k, with total deaths as the dependent variable, and the likelihood of a successful trace for a random contact as the independent variable. Intuitively, one would expect an inverse relationship where an increase in the likelihood of a successful trace for a random contact would result in a lower total death count. The results I've been seeing are counter to this intuition.

Below is a snippet of the code I'm running. I run 50 trials for each 0.1 increment of the manual_traceable_fraction_random parameter (ranging from 0.1 to 1.0).

        if step == lockdown_at:
            model.update_running_params("lockdown_on", 1)
        if step == lockdown_at + 30:
            model.update_running_params("lockdown_on", 0)
            model.update_running_params("self_quarantine_fraction", 0.5 )
            model.update_running_params("quarantine_household_on_positive", 1 )
            model.update_running_params("quarantine_household_on_symptoms", 1 )
            model.update_running_params("manual_trace_on", 1 )
            model.update_running_params("manual_trace_on_positive", 1 )
            model.update_running_params("manual_trace_delay", 1 )
            model.update_running_params("manual_trace_n_workers", 30 )
            model.update_running_params("manual_traceable_fraction_random", 0.5 )
        df = pd.DataFrame(m_out)

Here's a plot of the day 200 average results over 50 trials per setting. As you can see, the trend appears to be heading the wrong direction. Also, I'm not sure why there's a blip at 0.3; I checked the code and it's consistent with the others.

![image](https://user-images.githubusercontent.com/6155445/87248967-8b637900-c419-11ea-85a6-4644ecc5b1f0.png)

**Comment by roberthinch** [comment]
It seems as if manual contact tracing is having very little effect here, however, from the code snippet that you posted it looks like nothing is being done once somebody is traced. Try setting:

'model.update_running_params("quarantine_on_traced", 1 )'

which is required to give the instruction to quarantine once traced. Note, by default there is not 100% compliance.
