### ISSUE TITLE
Modelling Vaccinations

### ISSUE THREAD

**Issue by roberthinch** [BDI-pathogens/OpenABM-Covid19#186]
Vaccinations are now available and substantial numbers of people are being vaccinated in some countries. As well as protecting those vaccinated, they can lower the spread of the virus due to a greater proportion of the population having immunity. Therefore, modelling vaccinations is important for both modelling the future trajectory of the pandemic and evaluating different vaccination strategies.

Vaccines would be simple to model if people immediately gained 100% immunity to the virus upon being vaccinated. However, this is not the case, with it taking time for immunity to develop post-vaccination and the requirement of booster jabs. On top of this, vaccines do not give 100% protection, with some people not gaining immunity or only gaining partial immunity. The level of immunity may also be age dependent, given that younger people have stronger immune responses. Additionally, some vaccines may only prevent severe symptoms without preventing viral loads growing to levels where the virus can be transmitted. Finally, most vaccines only offer protection for a limited period (e.g. 6 months - 5 years), therefore immunity from a vaccine will wane over time.

At the moment there is insufficient data from the vaccine trials to fully evaluate the efficacy and dynamics of the vaccines. Therefore as a first step we propose a simple model for vaccinations which can be parameterised from the released data from the vaccine trials and knowledge of other vaccines:

1. On receiving the first dose of a vaccine, a proportion of people (e.g. 60%) gain complete immunity after a period of times (e.g. 2 weeks)
2. On receiving a booster, a further proportion of people (e.g. 30%; so 90% immunity with both injections) gain complete immunity after a period of time (e.g. 2 weeks)
3. People protected by the vaccine can either never infect others OR if they are infected have a standard asymptomatic response (in which they could transmit to others).
4.  Protection from the vaccine (for those with a response) lasts for a set period of time (e.g. 1 year) and then wanes over time with a proportion losing infection at each time step (e.g. geometrically distributed with a mean of 6 months)
5. Response to the vaccine does not vary by age

**Comment by ewan-wakeman** [comment]
Hi @roberthinch,

Great to see this up and the outlined approach. I've been thinking about this over the past week or so and thought best to document them here.

1. As vaccination roll-out will proceed at different rates for different groups, assuming `get` and `set` methods for age-related model variables would be exposed through Python API. Is this the case and if so would it use `AGE_GROUP` enums or `AGE_TYPES`?
2. In terms of how immunity is expressed in the model I'm assuming would be an attempt to some parameters for individuals upon vaccination. I could see this be either reducing `individual->hazard` to a lower value or changing `individual->*next_disease_event` to `ASYMPTOMATIC` or a new enum type which is much the same as `RECOVERED` but without having moved through an infected stage. Is one of the above approaches what you were thinking or were you planning something else entirely.
3. In terms of controlling vaccinations within an age group I imagine there are a few ways we could parameterise a vaccination programme:
    * Feed the model *proportions* of age groups to be vaccinated at regular intervals (e.g. weekly). This proportions type approach would mean calculating how number of vaccinations translate into proportions outside of the model but would avoid us *running out* of groups to vaccinate.
    * As above but feed smaller proportions for each timestep the model is run (i.e. daily vaccination amounts). Assume this may be preferable as this would allow for more realistic control and is largely how other variables are controlled currently. This may also be fed in as a mean and sd pair so exact numbers vaccinated on each timestep varies slightly.
    * Feed in *numbers* to be vaccinated for each interval/timestep. Assume this would be trickier from a model perspective as would need to know what to do when we run out of individuals in a group to vaccinate (e.g. do these vaccinations pass to the next age group).
    * Feed the model some kind of ratio and number of vaccinations expressing the likelihood of an individual to be selected based on know characteristics (e.g. we have 1000 vaccinations and those who are 80 plus are a factor of `x` more likely to be selected for vaccination than a reference group). This may be too complicated but could also get around issue of *over-selecting* from a specific age-group.
4. Do you envisage specific controls for work-related groups (e.g. medical professionals) who we know are following a particular vaccination programme independent of age?

Sorry these thoughts are a little loose at the moment but wanted to get them down and can continue to develop them.

Thanks
Ewan

**Comment by roberthinch** [comment]
Comments on response from ewan-wakeman:

1. The exact details of a vaccination programme are going to be very varied, so to try a complete parameterised programme would be very difficult (and likely a total mess). So, I think it is best to provide a few simple functions in the Python API and let the end user code the details themselves in Python (i.e. like the get/set functions you suggest).

2. I was not planning on changing the individual's hazard (this would be a form of partial immunity for everyone which probably inaccurate). The 2 versions I had in mind was for people who have had a response to the vaccination to either: on infection they all go down the asymptomatic route OR go to RECOVERED or a similar new state with similar properties (i.e. the 2nd/3rd things you suggest).

3. With a generic get/set functions, the user could code all these programmes easily in Python. There may be a couple of useful functions to add beyond the most basic "vaccinate this person", such as, "vaccinate_n_in_age_group_per_step".

4. Again doable by end user in Python using a couple of generic functions. I expect this is the type of thing which is to specialist to include in the code code.

**Comment by ewan-wakeman** [comment]
Just trying to sketch out a programme for using vaccinations in OpenABM and think the most straightforward route from our point of view would be simply to update the running parameters of the model (e.g. `model.update_running_params('vaccinate_n_per_timestep', 5000)` ) at certain points and then roll forward. Obviously in time we could get more precise with this if corresponding functions exist on the OpenABM side by combining this with enums from the model (e.g. `model.update_running_params('vaccinate_n_in_age_group_per_timestep_80', 200)` ). Could I just check whether this aligns with your current thinking on approach to implementing this feature?

I'm hoping to start writing some scripts to test this functionality this week, do you think it's likely there will be any code up on a branch this week or not? No pressure if not, just trying to figure out how quickly I should get to work on this. Let me know if you have any questions for me about anything I've said above.

**Comment by roberthinch** [comment]
Instead of adding additional parameters to the model, there will be a function on the Python model object which will allow you to vaccinate on each time step with the parameters defined in the Python code. I can potentially add the ability for it to repeat on each time step (instead of being called on each time-step in the Python code). Code is on my fork (vaccinate_model), the basic vaccine of individuals is working and tested, currently adding mass vaccinations.

**Comment by ewan-wakeman** [comment]
Thanks, that's super helpful. Looking through the test class now to get a sense of best approach on our side. Will keep an eye out for mass vaccinations as you work through those.
