### ISSUE TITLE
Missing method get_model_param_lockdown_elderly_on

### ISSUE THREAD

**Issue by sedim-dhsc** [BDI-pathogens/OpenABM-Covid19#224]
In Python, calling `model.get_param("lockdown_elderly_on")` raises `COVID19.model.ModelParameterException: Parameter lockdown_elderly_on not found`. This is due to the fact that `param.h` and `params.c` don't have the method `get_model_param_lockdown_elderly_on`. 

Thanks for the great lib
Dmitry

**Comment by roberthinch** [comment]
Fixed in PR#225
