### ISSUE TITLE
Question about installing OpenABM - Covid19

### ISSUE THREAD

**Issue by ZyRose1** [BDI-pathogens/OpenABM-Covid19#232]
How to install OpenABM-Covid19?
Although I looked at the tutorial for OpenABM-Covid19 on GitHub, I still can't download and use OpenABM-Covid19.

Looking forward to your reply！

**Comment by roberthinch** [comment]
The tutorial has a section called Compilation which explain how to install the Python version and a section called R Packaging  to install the R version. If this does not work please post the specific error message.
