### ISSUE TITLE
Fixing initial infected population

### ISSUE THREAD

**Issue by sanderbroos** [BDI-pathogens/OpenABM-Covid19#238]
Hello. For my project I would like to have multiple runs (with different random seeds) that start with the same initial infected population - so it is only the spread/dynamics of the simulation that would change. Is this possible with the current code? It seems that the only influence is setting the parameter "n_seed_infection", but is it for example possible to set that to zero and manually call the function "new_infection" for a certain specific set of people at the start to take the randomness out of that specific part of the setup?

**Comment by roberthinch** [comment]
By changing the initial random seed there will be multiple changes to the model beyond just who is initially infected, for example the network construction uses random variables (so the people are not the same), but this is one of many. 

Given the many uses of random variables within the simulation, it is unclear how to interpret isolating a subset of them.
