### ISSUE TITLE
Recent updates involving hospital model

### ISSUE THREAD

**Issue by aaron-scheffler** [BDI-pathogens/OpenABM-Covid19#94]
Hello,

I am getting caught up with some of the model developments, including the addition of the hospital model.

Is it still possible to run the IBM without the detailed hospital modeling, for example by setting 
`read_hospital_param_file = False`?

Or does this default the model a set of predefined parameters for the hospital model?

Thank you and best regards,
Aaron

**Comment by roberthinch** [comment]
As long as `hospital_model_on=False` in the main parameters then it can be run with `read_hospital_param_file = False`. This is currently the default but will change in a few weeks once the hospital model is calibrated.

We've updated the examples in PR #93 so that they point to the default files.
