### ISSUE TITLE
Disconnect between parameters in tests/data and documentation

### ISSUE THREAD

**Issue by aaron-scheffler** [BDI-pathogens/OpenABM-Covid19#98]
Hello, 

I am seeking some clarification on the current status of the model and documentation. Early on, the baseline parameter values in tests/data/baseline_parameters.csv reflected the documented values in the covid19_model.pdf and the Parameters.pdf documents. The parameter values in baseline_parameters.csv now do not match documentation, particularly with respect to infection dynamics. For example, relative_susceptibility, infectious rate, etc...

Has the underlying model of infectious dynamics changed and thus the meaning of these parameters? I know that our knowledge of the disease is constantly changing and it would be great to know how these changes in baseline_parameters.csv are anchored to updates in literature and how they affect disease features (e.g. doubling time)? 

Thank you very much and best regards,
Aaron

**Comment by roberthinch** [comment]
That .pdf document is out of date (we're moving it to markdown so it is easier to keep track of changes). The values in baseline_parameters.csv are our latest understanding based upon a meta analysis of multiple sources. They mainly affect the details of who (i.e. by age) gets infected as opposed to macro features such as doubling time which we calibrate the infectious_rate parameter to (baseline is fitted to 3.5 days doubling time).
