### ISSUE TITLE
Why install python dataclasses?

### ISSUE THREAD

**Issue by RossBoylan** [BDI-pathogens/OpenABM-Covid19#99]
I'm running Python 3.7, which you say is required.
The python package `dataclasses` says it is a backport of `dataclasses` from 3.7 for 3.6.
So why is it being installed by `make install`?

**Comment by al626** [comment]
Previously, 3.6 was the minimum viable python version, which needed a backport of dataclasses.

Given we're now on 3.7, this should be dropped.

**Comment by al626** [comment]
Removed the above referenced commit fix - sounds like a discussion needs to be had to see which path to go down

**Comment by RossBoylan** [comment]
If the 3.6 is sufficient to run the application, though not the test suite, it might be good to continue to support it.  I don't know if python has a way to express dependencies conditional on the python version.  I'm also fuzzy on what happens if dataclasses is installed in a 3.7 environment, but I'd guess the installed package hides the system one.  I guess either one should function OK.
